### ISSUE TITLE
Constant `pathlib.Path` instances escape the fake-file-system

### ISSUE THREAD

**Issue by a-recknagel** [pytest-dev/pyfakefs#1045]
**Describe the bug**
If I have a fully resolved `pathlib.Path` object (such as ist returned by e.g. `pathlib.Path.cwd()`) that is created outside of the scope of the `fakefs` context (I use pytest's `fs` fixture), things stop working.

**How To Reproduce**
```python
# my code
from pathlib import Path

PATH = Path.cwd() / "my.conf"


def read_credentials():
    with open(PATH) as f:
        return f.read()


# my test
# from my_code import read_credentials, PATH
def test_read_credentials(fs):
    with open(PATH, "w") as f:
        f.write("foo")
    result = read_credentials()
        
    assert "foo" in result
```

Fails with
```text
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/me/dev/'
```
If both the code and the test call `Path.cwd()` instead of using the constant, the test works. It also works if I use `Path(".")` as a constant instead. So I'm not looking for a workaround, this post is specifically about global resolved `pathlib.Path` instances that might not be as easily avoidable.

**My environment**
```bash
Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python 3.12.1 (main, Jan 26 2024, 16:46:43) [GCC 11.3.0]
pyfakefs 5.5.0
pytest 8.2.2
```

**Comment by mrbean-bremen** [comment]
Well, that's expected, and I honestly don't know what to about this.
If you initialize the path globally, it is initiallized with the real path, which does not exist in the fake filesystem, so open will fail in the fake filesystem call. This is the same behavior as you get with any mocking with respect to global variables.

If you want to replicate the real fs file structure into the fake fs, you can map the parent directory into the fake fs (or just create that path in the test). 
If you want to use `cwd` from the fake fs instead of the real fs (I guess you expect that), you have to reload the definition of the path inside the test - which is of course only possible if it lives in another module than the test. You could do that using the [modules_to_reload](https://pytest-pyfakefs.readthedocs.io/en/latest/usage.html#modules-to-reload) argument, or just by using `importlib.reload`. There is no realistic way to reslove this rather than re-executing the code creating the global variable (e.g.) inside the test.

**Comment by a-recknagel** [comment]
I hadn't tried `importlib.reload` yet, it failed me a couple of times in the past so I've stopped considering it since then. Anyway, I guess what I expected, without having looked at the code yet, is that `open` or `pathlib.Path.open` get patched by `fakefs` and they may have a chance to map the path even if it's been resolved already.

**Comment by mrbean-bremen** [comment]
> I guess what I expected, without having looked at the code yet, is that `open` or `pathlib.Path.open` get patched by `fakefs` and they may have a chance to map the path even if it's been resolved already.

This is what happens - `open` is patched and tries to create the file in a directory that does not exist in the fake filesystem. There is no way I can think of, that it could deduce that the path had been created before using `cwd` and recreate it using the patched `cwd` (I guess this is what you mean by "map the path"?).

**Comment by a-recknagel** [comment]
it wouldn't be a good solution, but for my problem specifically this pseudocode would solve it:
```python
def patched_open(path: "PathLike") -> "FileHandle":
    if path.startswith(original_cwd()):
        path = patched_cwd() / path.relpath(original_cwd()) 
    return path.open()
```
I guess it would be quite bad if I saw in the debugger that the filehandle that I got back points to a different location than the path that I passed to `open`... feel free to close this, I don't see a way to solve this problem in a way that causes less issues than the initial problem.

**Comment by mrbean-bremen** [comment]
> I don't see a way to solve this problem in a way that causes less issues than the initial

Me neither. This is one of the limitations of patching in pyfakefs, and in Python generally. Thanks for the report and the investigation anyway!
