### ISSUE TITLE
Simulate no file system

### ISSUE THREAD

**Issue by kasuteru** [pytest-dev/pyfakefs#701]
**Is your feature request related to a problem? Please describe.**
I have a program that, for data security reasons, should never persist anything to local storage if deployed in the cloud. Instead, any input / output needs to be written to the connected (encrypted) storage instead.

To allow deployment locally as well as to multiple clouds, I am using the very useful [fsspec](https://filesystem-spec.readthedocs.io/en/latest/). However, other developers are working on the project as well, and I need a way to make sure that they aren't *accidentally* using local File I/O methods - which may pass unit tests, but fail when deployed to the cloud.

**Describe the solution you'd like**
pyfakefs already mock replaces the local I/O methods, so it seems like the perfect starting point for what I have in mind: Instead of simulating e.g. a Linux environment under Windows, it could replace any file system access with methods that simply raise an error when used. This way, any function that tries to rely on local storage instead of the connected cloud storage would be discovered in tests.

**Describe alternatives you've considered**
I currently have a stackoverflow question open asking for alternatives, but haven't received any so far. The only one that comes to my mind currently is to write this from scratch myself - which seems like a bad alternative given how mature this library is. 

- *"Simply telling the others to not use the local fs"* isn't really an alternative - I have caught myself accidentally doing it since it is just so ingrained in standard coding practice, so I would really like to test for it.
- Checking for `import os` or similar in pre-commit doesn't seem feasible as well, since this can be used for other stuff (e.g. read the environment) and file I/O often happens hidden (e.g. `pandas.read_csv()`)

What do you think, would this be a suitable enhancement?

**Comment by mrbean-bremen** [comment]
Hm, that is not really in scope for pyfakefs as a test framework/plugin, and it is also not bullet-proof (see [limitations](http://jmcgeheeiv.github.io/pyfakefs/release/intro.html#limitations)). So, if you want to use this to run your production code on, it is probably not the best idea.

What you would need is some enviroment where your code is run only after the fake filesystem is initialized (by creating a `Patcher` object and calling `setUp` on it). One way to ensure a file system that is not writable could be to set the file system size to 0 (though you would have to do this for each mount point if you use several):

```py
    p = Patcher()
    p.setUp()
    p.set_disk_uage(0)  # set the size of the root mount point ("/" under Linux/MacOS, "C:\" under Windows)
```
Any write operation to this filesystem would raise an `OSError` (out of space), and any read operation would fail as there are no files in the filesystem. Still, the above applies: there may be cases where the I/O functions are not mocked, because they are implemented via C functions instead of the standard I/O functions. Also this may not play nice with multiprocessing and multithreading code. With the complexity of your application the probability increases, that something won't work as expected.

Adding special code for that use case would probably just mean to raise some specific exception (instead of `OSError`) on any attempy to read/write, but all mentioned limitations would apply anyway.

**Comment by kasuteru** [comment]
Thanks for the hint with setting disk usage, I'll give it a try. To be honest, it does not have to be perfect - the alternative currently is not testing for it at all, so if it turns out to be an easy way to reduce potential mistakes, we'll use it. In the end, for all complex code, testing can only help find mistakes but not guarantee that there are none.

I assume that stuff like os.listdir() will keep working even though `disk_usage == 0`? I might try to extend this (make it unfunctional) with a PR if I actually include the Patcher in our testing env.

**Comment by mrbean-bremen** [comment]
> I assume that stuff like os.listdir() will keep working

Yes, it would, though it would return an empty list, of course. If you see that this scenario is something you can actually use, I will have another look at this.

**Comment by kasuteru** [comment]
Thanks. Let me first try to integrate it into my tests. If that is successful, I will try to see whether it makes sense to extend this functionality to os.listdir() et al. as well, and come back to you.

**Comment by mrbean-bremen** [comment]
@kasuteru - any news here?

**Comment by mrbean-bremen** [comment]
I'm closing this because of missing feedback - feel free to reopen it if you still need this.
