### ISSUE TITLE
Webpage on PyPI out-of-date

### ISSUE THREAD

**Issue by stefan6419846** [pytest-dev/pyfakefs#746]
I just had a look at the PyPI page for this project (https://pypi.org/project/pyfakefs/), which seems to be out-of-date and therefore points to an invalid URL: The homepage refers to http://pyfakefs.org/, which states that the corresponding account has been suspended.

There are some other invalid URLs as well, but these have already been fixed in #732 here at GitHub.

**Comment by mrbean-bremen** [comment]
Thank you - I missed that one! Will fix this now, but it will only show up at the next release...

**Comment by buhtz** [comment]
I know this is maybe unusual but because of security reasons and the burden of extra maintenance I suggest to drop the PyPi package.

It is damn easy to install python packages directly from a GitHub URL (`python3 -m pip install git+https....`) or from an zip/tar archive (the release files). No need for PyPi.

And much more stable there are also the distro maintainers offering packages.

But leave an empty package there or someone will hijack your package name and add bad code into it.

**Comment by mrbean-bremen** [comment]
I don't think so. Not everybody wants to (or is able to due to company rules) to install from the development branch. True, it would be possible to install for a certain tag, but still the PyPi packages are expected, and installing from there is integrated into most workflows. Removing them would break a lot of code. As for the distro maintainers - this is true only for Linux, and not for all distros for that matter. It is unlikely that MS will distribute packages with Windows any time soon :)
Also, there is no maintenance overhead here. There is a release workflow that does the publishing to PyPi automatically for a release.

**Comment by mrbean-bremen** [comment]
Fixed with release 5.1.0.
